### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by stfsy** [shaheen-syed/Twitter-Sentiment-Analysis#1]
hi @shaheen-syed,

super interesting what you have published here. I would like to reuse parts of your research for my own., but you did not add a license. Did you intentionally **not** add a license?

**Comment by shaheen-syed** [comment]
I just added the license. Feel free to use any or all parts of the code. Citation to the published paper [https://doi.org/10.1098/rsos.190473](https://doi.org/10.1098/rsos.190473) would be appreciated.
